2020-10-25 18:00:18,410 ERROR: Exception on /champselect [GET] [in e:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "e:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Fabian\Desktop\Hopdi\Prosjekter\bordplassering\app\routes.py", line 221, in found
    return render_template("index_flaskpage.html", obj=overView[identifier],user= current_user,allergiesList=allergyOverview)
KeyError: 'champselect'
